### ISSUE TITLE
Some errors when running the script

### ISSUE THREAD

**Issue by Metoku** [Animenosekai/genshin-presence#1]
![image](https://user-images.githubusercontent.com/59681368/148752223-c93e31a8-26dc-4eee-aa63-54f3b89e4512.png)
So I after I configured and installed the requirements I am getting errors. I don't know if I did something wrong.

**Comment by Animenosekai** [comment]
Yup just saw that Gunicorn was not supported on Windows so I guess I'll change the dependencies on Nasse and drop Nasse requirement on this project for now!

**Comment by Metoku** [comment]
Oh okay thanks I will close the issue when its dropped.

**Comment by Animenosekai** [comment]
Should be solved with 6ad101dc8be0469a4cf90290e3c5604054ba61d1
